site_name: theme.park Docs
site_description: Here you can find installation and setup details for all the themes in the GilbN/theme.park repo
site_author: GilbN
site_url: https://docs.theme-park.dev

repo_url: https://github.com/GilbN/theme.park/
repo_name: GilbN/theme.park
edit_uri: https://github.com/GilbN/tp-docs/edit/main/docs/

plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
  - macros
  - redirects:
      redirect_maps:
        discord.md: "https://discord.gg/HM5uUKU"
        dockerhub.md: "https://hub.docker.com/u/gilbn"
        github.md: "https://github.com/gilbn"
        ghcr.md: "https://github.com/users/GilbN/packages/container/package/theme.park"
        donate.md: "https://docs.theme-park.dev/#donation"
        themes.md: "https://docs.theme-park.dev/themes/sonarr/"
        docker-mods.md: "https://docs.theme-park.dev/setup/#docker-mods"
        hotio.md: "https://docs.theme-park.dev/setup/#hotio-containers-s6-overlay-images"

markdown_extensions:
  - pymdownx.snippets
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Setup: setup.md
  - Themes:
      ⚙️ App supports custom CSS: /themes/
      🐳 Supports Docker Mods: /docker-mods/
      🔥 Supports Hotio / S6-Overlay images: /hotio/
      ⚠️ Require Special Setup: /themes/
      ❌ Deprecated: /themes/
      Sonarr 🐳🔥: themes/sonarr.md
      Radarr 🐳🔥: themes/radarr.md
      Lidarr 🐳🔥: themes/lidarr.md
      Readarr 🐳🔥: themes/readarr.md
      Prowlarr 🐳🔥: themes/prowlarr.md
      Whisparr 🐳🔥: themes/whisparr.md
      Bazarr 🐳🔥: themes/bazarr.md
      Plex 🐳🔥: themes/plex.md
      Jellyfin ⚙️: themes/jellyfin.md
      Emby 🐳⚠️: themes/emby.md
      Overseerr: themes/overseerr.md
      Tautulli 🐳🔥: themes/tautulli.md
      Nzbget 🐳🔥: themes/nzbget.md
      ruTorrent 🐳🔥: themes/rutorrent.md
      Sabnzbd 🐳🔥⚠️: themes/sabnzbd.md
      VueTorrent 🐳🔥⚠️: themes/vuetorrent.md
      qBittorrent 🐳🔥⚠️: themes/qbittorrent.md
      Deluge 🐳: themes/deluge.md
      Jackett 🐳🔥: themes/jackett.md
      Librespeed 🐳: themes/librespeed.md
      Synclounge 🐳: themes/synclounge.md
      Lazylibrarian 🐳: themes/lazylibrarian.md
      CalibreWeb 🐳⚠️: themes/calibreweb.md
      Transmission 🐳: themes/transmission.md
      Mylar 3 🐳⚠️: themes/mylar3.md
      Duplicati 🐳: themes/duplicati.md
      Nginx-Proxy-Manager 🔥: themes/nginx-proxy-manager.md
      Xbackbone ⚙️: themes/xbackbone.md
      Filebrowser ⚙️: themes/filebrowser.md
      Organizr ⚙️: themes/organizr.md
      Unraid ⚙️: themes/unraid.md
      Ombi ⚙️: themes/ombi.md
      Gitea ⚙️: themes/gitea.md
      Pihole ⚠️: themes/pihole.md
      Dozzle ⚠️: themes/dozzle.md
      Bitwarden ⚠️: themes/bitwarden.md
      Vaultwarden ⚠️: themes/bitwarden/#vaultwarden
      Nzbhydra2: themes/nzbhydra2.md
      Portainer: themes/portainer.md
      Guacamole: themes/guacamole.md
      Netdata: themes/netdata.md
      Requestrr: themes/requestrr.md
      Adguard: themes/adguard.md
      Gaps: themes/gaps.md
      Duplicacy: themes/duplicacy.md
      Kitana: themes/kitana.md
      Resilio-Sync: themes/resilio-sync.md
      Moviematch: themes/moviematch.md
      Petio: themes/petio.md
      Flood: themes/flood.md
      Uptime-Kuma: themes/uptime-kuma.md
      TheLounge ❌🐳: themes/thelounge.md
      Grafana ❌⚙️: themes/grafana.md
      Monitorr ❌⚙️: themes/monitorr.md
      Logarr ❌⚙️: themes/logarr.md
      PLPP ❌: themes/plpp.md
      Webtools ❌: themes/webtools.md
  - Addons:
      Addons: themes/addons/index.md
      Sonarr:
        4K Logo: themes/addons/sonarr/4k-logo/index.md
        Sonarr 4K Text Logo: themes/addons/sonarr/sonarr-4k-text-logo/index.md
        Sonarr Darker: themes/addons/sonarr/sonarr-darker/index.md
        Sonarr Text Logo: themes/addons/sonarr/sonarr-text-logo/index.md
      Radarr:
        4K Logo: themes/addons/radarr/4k-logo/index.md
        Radarr Darker: themes/addons/radarr/radarr-darker/index.md
        Alternative Calendar: themes/addons/radarr/alt-calendar/index.md
      Readarr:
        Alternative Logo: themes/addons/readarr/alt-logo/index.md
        Readarr Darker: themes/addons/readarr/readarr-darker/index.md
        Alternative Calendar: themes/addons/readarr/alt-calendar/index.md
      Bazarr:
        4K Logo: themes/addons/bazarr/4k-logo/index.md
        Bazarr Darker: themes/addons/bazarr/bazarr-darker/index.md
      Lidarr:
        Lidarr Darker: themes/addons/lidarr/lidarr-darker/index.md
        Alternative Calendar: themes/addons/lidarr/alt-calendar/index.md
      Prowlarr:
        Prowlarr Darker: themes/addons/prowlarr/prowlarr-darker/index.md
      Whisparr:
        Whisparr Darker: themes/addons/whisparr/whisparr-darker/index.md
        Alternative Calendar: themes/addons/whisparr/alt-calendar/index.md
      Organizr: themes/addons/organizr/index.md
      Unraid:
        Retro Terminal: themes/addons/unraid/login-page/retro-terminal/index.md
        Alien: themes/addons/unraid/login-page/alien/index.md
        Fallout: themes/addons/unraid/login-page/fallout/index.md
      Plex:
        Alternative Logo: themes/addons/plex/plex-alt-logo/index.md
        Overseerr Side Menu: themes/addons/plex/overseerr-side-menu/index.md
  - Theme Options:
      Theme Options: theme-options/index.md
      Organizr: theme-options/organizr.md
      Dark: theme-options/dark.md
      Dracula: theme-options/dracula.md
      Aquamarine: theme-options/aquamarine.md
      Space Gray: theme-options/space-gray.md
      Plex: theme-options/plex.md
      Hotline: theme-options/hotline.md
      Hotpink: theme-options/hotpink.md
      Overseerr: theme-options/overseerr.md
      Nord: theme-options/nord.md
      Maroon: theme-options/maroon.md
  - Community Themes:
      Community Themes: community-themes/index.md
      Infinity Stone Themes:
        Mind: community-themes/infinity-stone-themes/mind.md
        Soul: community-themes/infinity-stone-themes/soul.md
        Reality: community-themes/infinity-stone-themes/reality.md
        Power: community-themes/infinity-stone-themes/power.md
        Space: community-themes/infinity-stone-themes/space.md
        Time: community-themes/infinity-stone-themes/time.md
      OneDark: community-themes/onedark/index.md
      Blackberry Themes: community-themes/blackberry-themes/index.md
      Pine Shadow: community-themes/pine-shadow/index.md
      TrueBlack: community-themes/trueblack/index.md
      Ibracorp: community-themes/ibracorp/index.md
      Hotline-Old: community-themes/hotline-old/index.md
  - Custom Themes: custom/index.md
  - Support: /discord
  - Donate: /donate

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  favicon: site_assets/favicon.ico
  logo: site_assets/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: red
      accent: light green

extra:
  homepage: https://github.com/GilbN/theme.park
  social:
    - icon: fontawesome/solid/heart
      link: "https://docs.theme-park.dev/donate"
      name: Donate
    - icon: fontawesome/brands/discord
      link: "https://docs.theme-park.dev/discord"
      name: Discord
    - icon: fontawesome/brands/docker
      link: "https://github.com/users/GilbN/packages/container/package/theme.park"
      name: Docker
    - icon: fontawesome/brands/github
      link: "https://github.com/gilbn"
      name: GitHub
  addons:
    sonarr:
      4K Logo:
        path: themes/addons/sonarr/4k-logo
      Sonarr 4K Text Logo:
        path: themes/addons/sonarr/sonarr-4k-text-logo
      Sonarr Darker:
        path: themes/addons/sonarr/sonarr-darker
      Sonarr Text Logo:
        path: themes/addons/sonarr/sonarr-text-logo
    radarr:
      4K Logo:
        path: themes/addons/radarr/4k-logo
      Radarr Darker:
        path: themes/addons/radarr/radarr-darker
      Alternative Calendar:
        path: themes/addons/radarr/alt-calendar
    readarr:
      Alternative Audiobook Logo:
        path: themes/addons/readarr/alt-logo
      Readarr Darker:
        path: themes/addons/readarr/readarr-darker
      Alternative Calendar:
        path: themes/addons/readarr/alt-calendar
    bazarr:
      4K Logo:
        path: themes/addons/bazarr/4k-logo
      Bazarr Darker:
        path: themes/addons/bazarr/bazarr-darker
    lidarr:
      Lidarr Darker:
        path: themes/addons/lidarr/lidarr-darker
      Alternative Calendar:
        path: themes/addons/lidarr/alt-calendar
    prowlarr:
      Prowlarr Darker:
        path: themes/addons/prowlarr/prowlarr-darker
    whisparr:
      Whisparr Darker:
        path: themes/addons/whisparr/whisparr-darker
      Alternative Calendar:
        path: themes/addons/whisparr/alt-calendar
    organizr:
      Organizr Glass:
        path: themes/addons/organizr
    unraid:
      Alien:
        path: themes/addons/unraid/login-page/alien
      Fallout:
        path: themes/addons/unraid/login-page/fallout
      Retro Terminal:
        path: themes/addons/unraid/login-page/retro-terminal
    plex:
      Overseerr Side Menu:
        path: themes/addons/plex/overseerr-side-menu
      Alternative Logo:
        path: themes/addons/plex/plex-alt-logo
  themes:
    - aquamarine
    - hotline
    - hotpink
    - dracula
    - dark
    - organizr
    - space-gray
    - overseerr
    - plex
    - nord
    - maroon

  community_themes:
    - mind
    - power
    - reality
    - soul
    - space
    - time
    - onedark
    - hotline-old
    - blackberry-abyss
    - blackberry-amethyst
    - blackberry-carol
    - blackberry-dreamscape
    - blackberry-flamingo
    - blackberry-hearth
    - blackberry-martini
    - blackberry-pumpkin
    - blackberry-royal
    - blackberry-shadow
    - blackberry-solar
    - blackberry-vanta
    - trueblack
