name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build documentation
        run: mkdocs build --config-file mkdocs.yml

      - name: Deploy to gh-pages-develop branch
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"

          git checkout -b gh-pages-develop
          rm -rf ./*
          mv ./site/* .
          rm -r ./site
          git add -A
          git commit -m "Deploy documentation to gh-pages-develop branch"
          git push origin gh-pages-develop
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.GITHUB_TOKEN }}
